import React, { useState, useEffect } from 'react';
import { 
  Activity, 
  RefreshCw 
} from 'lucide-react';

export default function AIFinancialHealth({ user }) {
  const [loading, setLoading] = useState(true);
  const [healthData, setHealthData] = useState(null);

  useEffect(() => {
    fetchHealthData();
  }, []);

  const fetchHealthData = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem('token');
      const res = await fetch('/api/ai/financial-health', {
        headers: { Authorization: `Bearer ${token}` }
      });
      const result = await res.json();
      if (result.success) {
        setHealthData(result);
      }
    } catch (err) {
      console.error('Health data fetch failed:', err);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="glass-panel" style={{ padding: '60px', textAlign: 'center', color: 'var(--text-muted)' }}>
        <RefreshCw size={32} className="spin-animation" style={{ animation: 'spin 1.5s linear infinite', margin: '0 auto 16px auto', color: 'var(--primary)' }} />
        <h3 style={{ color: 'var(--text-primary)' }}>AI Financial Diagnostic Engine is computing 360° health matrix...</h3>
        <p style={{ fontSize: '0.85rem', marginTop: '8px' }}>Evaluating savings ratio, emergency liquid buffer, debt-to-income, and cashflow stability.</p>
      </div>
    );
  }

  const score = healthData?.overallScore || 850;
  const pillars = healthData?.pillars || { savingsRatio: 220, emergencyBuffer: 210, creditStability: 220, cashflowVelocity: 200 };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '28px' }}>
      
      {/* Header Banner */}
      <div className="glass-panel" style={{ padding: '28px', background: 'linear-gradient(135deg, #e6f4ee 0%, #ffffff 100%)', border: '1px solid rgba(45, 138, 104, 0.25)' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '8px' }}>
              <div style={{ background: '#e6f4ee', color: 'var(--primary)', padding: '8px', borderRadius: '10px' }}>
                <Activity size={22} />
              </div>
              <h2 style={{ fontSize: '1.4rem', fontWeight: 800, color: 'var(--text-primary)' }}>360° AI Financial Health Diagnostics</h2>
              <span className="badge badge-success" style={{ fontSize: '0.7rem' }}>AI Diagnostics</span>
            </div>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem', maxWidth: '700px' }}>
              Comprehensive real-time financial health score (0-1000) generated by analyzing your balance reserves, cash flow stability, debt ratios, and emergency liquidity.
            </p>
          </div>

          <button onClick={fetchHealthData} className="btn-secondary" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <RefreshCw size={16} /> Re-Calculate
          </button>
        </div>
      </div>

      {/* Score Overview Row */}
      <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 1.8fr', gap: '24px' }}>
        
        {/* Main Circular Score Box */}
        <div className="glass-panel" style={{ padding: '32px', textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
          <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 600 }}>
            Overall Health Index Score
          </span>

          <div style={{ 
            position: 'relative', 
            width: '150px', 
            height: '150px', 
            borderRadius: '50%', 
            background: `conic-gradient(#2d8a68 ${(score / 1000) * 100}%, #e4eee9 0)`,
            display: 'flex',
            alignItems: 'center',
            justify: 'center',
            margin: '20px 0',
            boxShadow: '0 4px 20px rgba(45, 138, 104, 0.2)'
          }}>
            <div style={{ width: '120px', height: '120px', borderRadius: '50%', background: '#ffffff', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
              <span style={{ fontSize: '2.2rem', fontWeight: 900, color: 'var(--primary)' }}>{score}</span>
              <span style={{ fontSize: '0.65rem', color: 'var(--text-muted)' }}>/ 1000 EXCELLENT</span>
            </div>
          </div>

          <p style={{ fontSize: '0.82rem', color: 'var(--text-muted)', maxWidth: '280px' }}>
            Your account health places you in the top <strong>5% of resilient savers</strong>. Keep building your emergency fund buffer.
          </p>
        </div>

        {/* 4 Pillars Breakdown */}
        <div className="glass-panel" style={{ padding: '28px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
          <h3 style={{ fontWeight: 700, fontSize: '1.05rem', marginBottom: '16px', color: 'var(--text-primary)' }}>4 Pillars Health Breakdown</h3>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            
            {/* Pillar 1 */}
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', marginBottom: '6px' }}>
                <span style={{ color: 'var(--text-primary)', fontWeight: 600 }}>Savings Velocity Ratio</span>
                <span style={{ fontWeight: 700, color: 'var(--primary)' }}>{pillars.savingsRatio} / 250</span>
              </div>
              <div style={{ height: '8px', background: '#e4eee9', borderRadius: '4px', overflow: 'hidden' }}>
                <div style={{ height: '100%', width: `${(pillars.savingsRatio / 250) * 100}%`, background: 'var(--primary)' }} />
              </div>
            </div>

            {/* Pillar 2 */}
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', marginBottom: '6px' }}>
                <span style={{ color: 'var(--text-primary)', fontWeight: 600 }}>Emergency Liquid Buffer</span>
                <span style={{ fontWeight: 700, color: '#3b82f6' }}>{pillars.emergencyBuffer} / 250</span>
              </div>
              <div style={{ height: '8px', background: '#e4eee9', borderRadius: '4px', overflow: 'hidden' }}>
                <div style={{ height: '100%', width: `${(pillars.emergencyBuffer / 250) * 100}%`, background: '#3b82f6' }} />
              </div>
            </div>

            {/* Pillar 3 */}
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', marginBottom: '6px' }}>
                <span style={{ color: 'var(--text-primary)', fontWeight: 600 }}>Credit & Debt Utilization</span>
                <span style={{ fontWeight: 700, color: '#8b5cf6' }}>{pillars.creditStability} / 250</span>
              </div>
              <div style={{ height: '8px', background: '#e4eee9', borderRadius: '4px', overflow: 'hidden' }}>
                <div style={{ height: '100%', width: `${(pillars.creditStability / 250) * 100}%`, background: '#8b5cf6' }} />
              </div>
            </div>

            {/* Pillar 4 */}
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', marginBottom: '6px' }}>
                <span style={{ color: 'var(--text-primary)', fontWeight: 600 }}>Cashflow Stability Vector</span>
                <span style={{ fontWeight: 700, color: '#f59e0b' }}>{pillars.cashflowVelocity} / 250</span>
              </div>
              <div style={{ height: '8px', background: '#e4eee9', borderRadius: '4px', overflow: 'hidden' }}>
                <div style={{ height: '100%', width: `${(pillars.cashflowVelocity / 250) * 100}%`, background: '#f59e0b' }} />
              </div>
            </div>

          </div>
        </div>

      </div>

      {/* AI Action Plan */}
      <div className="glass-panel" style={{ padding: '24px' }}>
        <h3 style={{ fontWeight: 700, fontSize: '1.05rem', marginBottom: '16px', color: 'var(--text-primary)' }}>Prescriptive AI Action Plan</h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          {(healthData?.actionPlan || []).map(action => (
            <div 
              key={action.step} 
              style={{ 
                padding: '16px 20px', 
                borderRadius: '12px', 
                background: '#f8faf9', 
                border: '1px solid var(--border-color)',
                display: 'flex',
                justify: 'space-between',
                alignItems: 'center'
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
                <div style={{ background: '#e6f4ee', color: 'var(--primary)', width: '36px', height: '36px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 800 }}>
                  {action.step}
                </div>
                <div>
                  <h4 style={{ fontWeight: 600, fontSize: '0.95rem', color: 'var(--text-primary)' }}>{action.title}</h4>
                  <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '2px' }}>{action.description}</p>
                </div>
              </div>

              <span className="badge badge-success" style={{ fontSize: '0.75rem', padding: '6px 12px' }}>
                Impact: {action.impact}
              </span>
            </div>
          ))}
        </div>
      </div>

    </div>
  );
}
